### PR TITLE
Cleanup and dark mode

### PR DESCRIPTION
**Pull request by bexnoss**
This PR removes the leftover files from the old website and the unused files from the new one.

It also changes the HTML files to be rendered with Jekyll, allowing the use of templates. The data in download.html and addons.html is now in the YAML frontmatter at the top of the files. This makes updating much more convenient.

The last addition is a basic dark mode, enabled automatically by `@media (prefers-color-scheme: dark)`. The colors are from [Nord theme](https://www.nordtheme.com/) and fit in well with the blueish light theme.

The icon font has been optimized to only include the used icons. The original download icon was misaligned in the optimized font so it has been replaced with the very similar "cloud download" icon.

The copyright notice at the bottom has been removed. Copyright notices have been obsolete for a long while now and more importantly it had its own background gradient and it looked weird.

Closes https://github.com/transmission/transmission.github.io/issues/33
Closes https://github.com/transmission/transmission.github.io/pull/36
Closes https://github.com/transmission/transmission.github.io/issues/46
Closes https://github.com/transmission/transmission.github.io/issues/48
Closes https://github.com/transmission/transmission.github.io/pull/28
Closes https://github.com/transmission/transmission.github.io/pull/49

### CODE REVIEW

**Comment by bexnoss** [comment]
This was written for Jinja 4+ but GitHub pages ships Jinja 3.9.2, so this still needs a deploy action.

**Comment by bexnoss** [comment]
In the meantime there's a manually uploaded preview at https://bexnoss.github.io/transmissionbtcom/.

**Comment by ckerr** [comment]
The demo at bexnoss.github.io is looking pretty good!

@bexnoss lmk when this is out of draft mode

**Comment by ckerr** [comment]
> +2,560 −82,824

:rocket:

**Comment by bexnoss** [comment]
The choice of Jinja for static site generation was made because until recently Jinja was hardcoded into GitHub Pages. With [GitHub Pages: Custom GitHub Actions Workflows (beta)](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) any SSG can be used and I'd like to try some of them out and redo what is currently handled by Jinja.

I'll rebase and remove the Jinja port from this PR so the dark mode and cleanup can be merged without additional delay.

**Comment by bexnoss** [comment]
@ckerr this is ready now

**Pull request merged**
