### PR TITLE
add transmission-3.00

### PR DESCRIPTION
**Pull request by ckerr**
- [x] update Constants with info from https://github.com/transmission/transmission-releases/pull/3
  - [x] update sha256_dmg
  - [x] update sha256_tar
  - [x] update sha256_msi32
  - [x] update sha256_msi64
  - [x] update current_version
  - [x] update current_version_dmg
  - [x] update current_version_msi
  - [x] update current_version_tar

 - [x] update screenshots?

### CODE REVIEW

**Comment by mikedld** [comment]
Missing help/gtk/{3.0x->2.1x} symlink, or rather an updated version of the docs...

**Comment by mikedld** [comment]
Minimum macOS version in at least [download/index.html](https://github.com/transmission/transmission.github.io/blob/master/download/index.html#L94) needs to be bumped to 10.10.

**Comment by ckerr** [comment]
> Missing help/gtk/{3.0x->2.1x} symlink, or rather an updated version of the docs...

Agreed, but updating the docs doesn't block the 3.00 release and would be better off in a standalone PR anyway. Symlink added in 19d5e85

**Comment by ckerr** [comment]
> Minimum macOS version in at least download/index.html needs to be bumped to 10.10.

Fixed in 3beb287b98a78aac771f61728d9e4aa9164035d0

**Comment by livings124** [comment]
Merged the appcast changes into this branch.

**Pull request merged**
